website/website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('website_cozmo/', include('website_cozmo.urls')),
    path('admin/', admin.site.urls),
]

website/website_cozmo/urls.py
from django.urls import path
from . import views

app_name = 'website_cozmo'
urlpatterns = [
    path('', views.index, name='index'),
    path("home", views.home, name='home'),
    path("game", views.game, name='game'),
    path("libre", views.libre, name='libre'),
    path("histoire", views.histoire, name='histoire'),
    path("signout", views.signout, name='signout'),
    path("signup", views.signup, name='signup'),
    path("createprogram", views.createprogram, name='createprogram'),
    path("inscription_page", views.inscription_page, name='inscription_page')

]

website/website_cozmo/models.py
from django.db import models
 
# Create your models here.  
class Member(models.Model):
    username=models.CharField(max_length=50)
    firstname=models.CharField(max_length=50)
    lastname=models.CharField(max_length=50)
    password=models.CharField(max_length=20)
 
    def __str__(self):
        return self.firstname + " " + self.lastname
   
  
    class Meta:  
        db_table = "website_cozmo"



class Game(models.Model):
    title=models.CharField(max_length=50)
    description=models.CharField(max_length=200)
    file=models.CharField(max_length=200)
   
    class Meta:  
        db_table = "game"

website/website_cozmo/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from website_cozmo.models import Game
from website_cozmo.models import Member
import sys
import sqlite3
import cozmo
import random
from cozmo.objects import LightCube1Id, LightCube2Id, LightCube3Id
from cozmo.util import radians, degrees, distance_mm, speed_mmps


def on_cube_tapped(event, *, obj, tap_count, tap_duration, **kw): 
    global tapote
    global who_is_tapped


    tapote = True
    who_is_tapped = obj.object_id-1

def index(request):
    return render(request, 'website_cozmo/login.html')


def home(request):
    if request.method == 'POST':
        if Member.objects.filter(username=request.POST['username'], password=request.POST['password']).exists():
            member = Member.objects.get(username=request.POST['username'], password=request.POST['password'])
            return render(request, 'website_cozmo/home.html', {'user': member})
        else:
            context = {'msg': 'Invalid username or password'}
            return render(request, 'website_cozmo/login.html', context)


def signout(request):
    return render(request, 'website_cozmo/login.html')

def inscription_page(request):
    return render(request, 'website_cozmo/signup.html')


def signup(request):
    if request.method == 'POST':
        member = Member(username=request.POST['username'], password=request.POST['password'],  firstname=request.POST['firstname'], lastname=request.POST['lastname'])
        member.save()
        return render(request, 'website_cozmo/login.html')
    else:
        return render(request, 'signup.html')

 

def game(request):
    all_info = Game.objects.all()
    if request.method == 'POST':
        file_name = str(request.POST['file']) + '.py'
        file_path = "./game/" + file_name
        exec(open(file_path).read())


    return render(request, 'website_cozmo/game.html', {'games':all_info})


def libre(request):
    return render(request, 'website_cozmo/libre.html')

def histoire(request):
    return render(request, 'website_cozmo/histoire.html')

def createprogram(request):
    if(request.POST['content'] != ""):
            handle1=open('freeprogram.py','w+')
            handle1.write(request.POST['content'])
            handle1.close()
            saveout = sys.stdout                                   
            fsock = open('out.log', 'w')                             
            sys.stdout = fsock
            try:
                exec(open("freeprogram.py").read())
            except Exception as error:
                print(error)
            sys.stdout = saveout                                     
            fsock.close() 
            fsockR = open('out.log', 'r')
            return render(request, 'website_cozmo/libre.html', {'log':fsockR.read()})

website/website_cozmo/templates/website_cozmo/game.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Jeu</title>
  </head>
  <body style="background-color: #ECEFF1;">
    
      <h1 style="text-align: center;">
        Voici les jeux disponible
      </h1>
     

    {% for game in games %}

    <div style="flex:1; flex-direction:column">
      <div style="flex: 1; flex-direction: row;">
        <div style="margin-left: 100px; margin-right: 200px; flex: 1; background-color: #BBDEFB; border-radius: 20px;">
            <p style="font-size:large; font-weight: bold; margin-left: 10px; text-align: center;"> {{ game.title }}</p>
            <div style="text-align: center;">
              <p>{{ game.description }}</p>
              <p>Cliques sur l'image pour lancer le jeu.</p>

            </div>
            <div style="text-align: center;">

              <form method="POST" action="{% url 'website_cozmo:game' %}">  
                {% csrf_token %}
                <input value="{{game.file}}" name="file" hidden/>
                <button type="submit">
                  <img src="https://img.nrj.fr/-Cip8r2hsGv13diYfNIhJ183Lvo=/0x177/smart/http%3A%2F%2Fimage-api.nrj.fr%2Fmedias%2Fnrjgames%2F2017%2F09%2Fanki-cozmo-test.jpeg" />
                </button>
              </form>

            </div>
        </div>

      {% endfor %}

      </div>
    </div>

    </body>
</html>

website/website_cozmo/templates/website_cozmo/histoire.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Histoire</title>
  </head>
  <body>
    <div style="text-align: center;">
      <h2>Histoire</h2>
    </div>
    <div style="display: flex;flex-direction: row; justify-content: start;">
      <div>
        <form method="POST" action="{% url 'website_cozmo:createprogram' %}">  
          {% csrf_token %}
          <textarea id="editor" name="content" style="width:50vw;height: 90vh;"></textarea>
          <button type="submit">RUN</button>
        </form>
        <div>
          <p style="text-decoration: underline;">Voici la sortie console</p>
          {% if log %}
          <p style="color: red;">
            {{log}} 
          </p>
          {% endif %}
        </div>
      </div>
      <div >
        <div style="margin: 50px; border-style: solid;"> <!--Histoire -->
          <div style="margin-left: 50px;">
            <h3 style="text-align: center;">Intitulé de l'histoire</h3>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
              Vivamus nec nulla pellentesque, fermentum nibh a, sagittis mi.
               Etiam erat libero, finibus eu massa eu, volutpat aliquet nisi.
                Integer vitae pretium libero. Integer commodo efficitur congue.
                 Aliquam vulputate pulvinar mauris vel aliquet. Mauris vel urna massa.
                  Mauris eu porttitor lorem.
                   Vestibulum faucibus orci eu dolor iaculis suscipit.</p>
            </div>    
        </div>
        <div>
          <div style="margin: 50px;border-style: solid;"> <!--Exercice -->
            <div style="margin-left: 50px;">
              <h3 style="text-align: center;">Intitulé de l'exercice</h3>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
                Vivamus nec nulla pellentesque, fermentum nibh a, sagittis mi.
                 Etiam erat libero, finibus eu massa eu, volutpat aliquet nisi.
                  Integer vitae pretium libero. Integer commodo efficitur congue.
                   Aliquam vulputate pulvinar mauris vel aliquet. Mauris vel urna massa.
                    Mauris eu porttitor lorem.
                     Vestibulum faucibus orci eu dolor iaculis suscipit.</p>
            </div>
           
          </div>
        </div>

      </div>  
    </div>
  
  </body>
</html>

website/website_cozmo/templates/website_cozmo/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Home</title>
  </head>
  <body style="background-color: #ECEFF1;">
    
      <h1 style="text-align: center;">
        Bonjour {{user.firstname}}
      </h1>
     
    <div style="flex:1; flex-direction:column">
      <div style="flex: 1; flex-direction: row;">


        <div style="margin-left: 100PX; margin-right: 200px; flex: 1; background-color: #BBDEFB; border-radius: 20px;">
          <p style="font-size:large; font-weight: bold; margin-left: 10px; padding-top: 10px;">Jouer</p>
          <div style="text-align: center;">
            <p>Jouer.</p>
              <a href="{% url 'website_cozmo:game' %}">
              <button style="border-radius: 10px; background-color: #F5F5F5;">Jouer</button>
            </a>
          </div>
        </div>

        <div style="margin-left: 100PX; margin-right: 200px; flex: 1; background-color: #BBDEFB; border-radius: 20px;">
          <p style="font-size:large; font-weight: bold; margin-left: 10px; padding-top: 10px;"> MODE Administrateur</p>
          <div style="text-align: center;">
            <p>Entrer dans le mode administrateur.</p>
            <a href="{% url 'website_cozmo:game' %}">
              <button style="border-radius: 10px; background-color: #F5F5F5;">Administrateur</button>
            </a>
            </div>
        </div>
  
       
      
        <div style="margin-left: 100PX; margin-right: 200px; flex: 1; background-color: #BBDEFB; border-radius: 20px;">
          <p style="font-size:large; font-weight: bold; margin-left: 10px; padding-top: 10px;">MODE Histoire</p>
          <div style="text-align: center;">
            <p>Entrer dans le mode histoire.</p>
            <a href="{% url 'website_cozmo:histoire' %}">
              <button style="border-radius: 10px; background-color: #F5F5F5;">Histoire</button>
            </a>
            </div>
        </div>

        <div style="margin-left: 100PX; margin-right: 200px; flex: 1; background-color: #BBDEFB; border-radius: 20px;">
          <p style="font-size:large; font-weight: bold; margin-left: 10px; padding-top: 10px;">MODE code libre</p>
          <div style="text-align: center;">
            <p>coder votre propre jeu facilement.</p>
            <a href="{% url 'website_cozmo:libre' %}">
              <button style="border-radius: 10px; background-color: #F5F5F5;">Coder</button>
            </a>
            </div>
        </div>
      </div>
    </div>
    
    <a href="{% url 'website_cozmo:signout' %}">
      <button>
        Déconnexion
      </button>
    </a>
  </body>
</html>

website/website_cozmo/templates/website_cozmo/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Accueil</title>
  </head>
  <body>
  </body>
</html>

website/website_cozmo/templates/website_cozmo/libre.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>MODE LIBRE</title>
  </head>
  <body style="background-color: #ECEFF1;">
    <div style="text-align: center;">
      <h2>Coder librement ci-dessous</h2>
      <form method="POST" action="{% url 'website_cozmo:createprogram' %}">  
        {% csrf_token %}
        <textarea id="editor" name="content" style="width:50vw;height: 90vh;"></textarea>
        <button type="submit">RUN</button>
      </form>

      <div>
        <p style="text-decoration: underline;">Voici la sortie console</p>
        {% if log %}
        <p style="color: red;">
          {{log}} 
        </p>
        {% endif %}
      </div>
  
    </div>

  </body>
</html>

website/website_cozmo/templates/website_cozmo/login.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Accueil</title>
  </head>
  <body>
    <div style="text-align: center;">
      <h2>Connectez vous au site !</h2>
      <p>Si vous n'avez pas de compte,
        <a href="{% url 'website_cozmo:inscription_page' %}">
          inscrivez-vous !
        </a>

      </p>

      <form method="POST" action="{% url 'website_cozmo:home' %}">  
        {% csrf_token %}
        <label>Nom d'utilisateur</label><br/>
        <input type="text" name="username" placeholder="Entrez le nom d'utilisateur" required="required"> <br/><br/>
       
        <label>Mot de passe</label> <br/>
        <input type="password" name="password" placeholder="Entrez le mot de passe" required="required"> <br/><br/>
        <input type="submit">
      </form>

    </div>
    <label> <span style="color: red;">{{ msg }}</span></label>

  </body>
</html>

website/website_cozmo/templates/website_cozmo/signup.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>S'inscrire</title>
  </head>
  <body>
    <div style="text-align: center;">
      <h2>Création de compte</h2>
      <p>Si vous avez déjà un compte,
        <a href="{% url 'website_cozmo:index' %}">
          connectez-vous !
        </a>
      </p>

      <form method="POST" action="{% url 'website_cozmo:signup' %}">  
        {% csrf_token %}
        <label>Nom d'utilisateur</label><br/>
        <input type="text" name="username" placeholder="Entrez le nom d'utilisateur" required="required"> <br/><br/>
        
        <label>Prénom</label><br/>
        <input type="text" name="firstname" placeholder="Entrez le nom d'utilisateur" required="required"> <br/><br/>
       
        <label>nom</label><br/>
        <input type="text" name="lastname" placeholder="Entrez le nom d'utilisateur" required="required"> <br/><br/>

        <label>Mot de passe</label> <br/>
        <input type="password" name="password" placeholder="Entrez le mot de passe" required="required"> <br/><br/>
        <input type="submit">
      </form>
    </div>

  </body>
</html>